### ISSUE TITLE
Primary sources list does not display references

### ISSUE THREAD

**Issue by marfox** [Wikidata/primarysources#105]
It is impossible for users to work with this tool, as they cannot see the reference URLs at all.

**Comment by tomayac** [comment]
Closing for the same reason and rationale https://github.com/google/primarysources/issues/106 was closed.

**Comment by marfox** [comment]
@tomayac, could you please reopen this and tag it as an open task?
I will move all of them to:
https://www.wikidata.org/wiki/Wikidata:Requests_for_comment/Semi-automatic_Addition_of_References_to_Wikidata_Statements

**Comment by tomayac** [comment]
Reopened upon @marfox' request and tagged as 'open task' to be [collected](https://www.wikidata.org/wiki/Wikidata:Requests_for_comment/Semi-automatic_Addition_of_References_to_Wikidata_Statements) centrally.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148165

Moving forward, please drop your comments onto that Phabricator ticket.
