### ISSUE TITLE
Display every piece of information needed for curation in one page

### ISSUE THREAD

**Issue by marfox** [Wikidata/primarysources#106]
Currently, if a user wants to curate one Item, he or she must:
1. scroll down to the first blue statement (see #38);
2. click on the reference URL and open it in a new page;
3. wait for a reload to proceed to the next statement (see #58).

The workflow can be smoother if the above issues are fixed and the reference URL is automatically opened inside the Item page.

**Comment by marfox** [comment]
The primary sources list may be a valid starting point for that, but needs #105 to be fixed.

**Comment by tomayac** [comment]
While I can fully relate to the non-optimal workflow, realistically we (Googlers) are not in the position to fix this time-wise :-/ The workflow was motivated by reasons outlined in the [paper](http://research.google.com/pubs/pub44818.html)—the tl;dr being to model the regular Wikidata item view as closely as possible—and tested in the userscript phase. Feel free to have a go and remodel the tool from scratch (probably on a different branch), we are happy to merge Pull Requests. I'm closing the issue for now as we unfortunately can't fix it (but again, the concern is fully justified).

**Comment by nemobis** [comment]
> we are happy to merge Pull Requests

If you want so, then you should at least label these issues with a tag that lets people find open tasks. Otherwise, just tell users to track their feature requests elsewhere, such as a wiki page on wikidata.org.

**Comment by tomayac** [comment]
Fair remark. Leaving this open as a proxy issue for UI improvements and creating a new label.

**Comment by marfox** [comment]
@nemobis, @tomayac, I'm collecting these kinds of requests here:
https://www.wikidata.org/wiki/Wikidata:Requests_for_comment/Semi-automatic_Addition_of_References_to_Wikidata_Statements

**Comment by marfox** [comment]
@tomayac, please reopen and tag as open tasks the closed issues that reference this one, so that I can keep track of them in the above Wikidata Request for comment

**Comment by tomayac** [comment]
Done. Thanks for the passion!

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148163

Moving forward, please drop your comments onto that Phabricator ticket.
