### ISSUE TITLE
Time values before year 1000 are not supported

### ISSUE THREAD

**Issue by marfox** [Wikidata/primarysources#108]
The exception is thrown [here](../blob/master/backend/persistence/Persistence.cc#L152).
Not sure which is the reason behind this decision.

Wikidata actually supports that, cf, for instance https://www.wikidata.org/wiki/Q46750

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148162

Moving forward, please drop your comments onto that Phabricator ticket.
