### ISSUE TITLE
Approve from listDialog errors with "Cannot read property 'source' of undefined"

### ISSUE THREAD

**Issue by tfmorris** [Wikidata/primarysources#109]
If you use the Primary Sources statement list dialog and click on "Approve" for one of the items, the progress bar spins forever and the console logs the error above.

The offending line is here:
https://github.com/google/primarysources/blob/master/frontend/freebase2wikidata.js#L1921

The statement gets added, but because the exception happens before the call to setStatementState, I suspect that the statement will get presented again, resulting in duplicates.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148160

Moving forward, please drop your comments onto that Phabricator ticket.
