### ISSUE TITLE
Fix Travis CI build

### ISSUE THREAD

**Issue by tfmorris** [Wikidata/primarysources#110]
It's been 3 months and dozens of builds since a build completed successfully.

https://travis-ci.org/google/primarysources/builds

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148158

Moving forward, please drop your comments onto that Phabricator ticket.
