### ISSUE TITLE
Merges / redirects aren't handled 

### ISSUE THREAD

**Issue by tfmorris** [Wikidata/primarysources#112]
The underlying error in #111 is a hard error and turns out to be caused by a merge of the target object https://www.wikidata.org/w/index.php?title=Q3608161&action=history which triggers a wikibase-validator-no-such-entity error from the API.

In case it's needed, the statement was:  data-statement-id="7560244" data-property="P1346" data-object="Q3608161"

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148155

Moving forward, please drop your comments onto that Phabricator ticket.
