### ISSUE TITLE
Include data source in statement edit comment

### ISSUE THREAD

**Issue by tfmorris** [Wikidata/primarysources#113]
Currently the comment is simply "Added via Wikidata:Primary sources tool"  It would be very useful to include the original data source, particularly as more sources are loaded into the tool.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148153

Moving forward, please drop your comments onto that Phabricator ticket.
