### ISSUE TITLE
Field value matching needs to check for regular expression P1793 before suggestion

### ISSUE THREAD

**Issue by brierjon** [Wikidata/primarysources#114]
Strings should check if P1793 exists for the matched fields and check if the compared values match formats before making a suggestion.

For example: FIPS 55-3 suggestions are a numerical string without the dash while values in Wikidata includes the dash in the string since P1793 for FIPS 55-3 applies \d\d-\d{5} for the field.

See Q668676 
Existing value imported from German Wikipedia 24-18750
Suggested value is 2418750 (the suggestion is not necessary as values match)

These are the same value with different formats which without this format check is receiving suggestions where the value exists.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148152

Moving forward, please drop your comments onto that Phabricator ticket.
