### ISSUE TITLE
Rewrite CONTRIBUTING.md

### ISSUE THREAD

**Issue by sjoerddebruin** [Wikidata/primarysources#116]
CONTRIBUTING.md should be rewritten to reflect the recent changes to this project.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148151

Moving forward, please drop your comments onto that Phabricator ticket.
