### ISSUE TITLE
Primary Source tool shouldn't suggest claims without sources

### ISSUE THREAD

**Issue by ChristianKleineidam** [Wikidata/primarysources#117]
I used the random primary source feature and it lead me to "https://www.wikidata.org/wiki/Q1063785". The Primary Source tool suggest that the person is a singer but it doesn't provide any sources for the claim.

It also does the same with claims about her having a degree at "Sonoda Women's University" and residence in Kōbe and Takarazuka.

Without a claim there no way for a user of the primary sources tool to verify whether it works correctly and the user should approve the claim.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148150

Moving forward, please drop your comments onto that Phabricator ticket.
