### ISSUE TITLE
The Primary Source tool should fill more fields for references

### ISSUE THREAD

**Issue by ChristianKleineidam** [Wikidata/primarysources#118]
The Primary Source tool knows more about the source than just the reference url. It should also add 
 "retrieved at" and "stated in".

Having "sourcing circumstances" "Primary Source tool" might also be very valuable for leaving good records about data providence. It would also make Wikidata users more aware of the impact the tool has.

**Comment by sjoerddebruin** [comment]
This is more the responsibility of the data sources than the tool itself.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148148

Moving forward, please drop your comments onto that Phabricator ticket.
