### ISSUE TITLE
Don't offer to add born in country X when the item already has born in city Y (with Y in X)

### ISSUE THREAD

**Issue by ChristianKleineidam** [Wikidata/primarysources#119]
When going to https://www.wikidata.org/wiki/Q1046833 Wikidata knows that Giorgi Melikishvili is born in Tbilisi (which happens to be the capital of Georgia). It has two sources for the claim.
Nevertheless the Primary Sources tool suggests adding "Georgia" to the location of birth. I think that isn't needed.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148147

Moving forward, please drop your comments onto that Phabricator ticket.
