### ISSUE TITLE
Last.fm links are to dynamic pages

### ISSUE THREAD

**Issue by ChristianKleineidam** [Wikidata/primarysources#120]
I look at https://www.wikidata.org/wiki/Q534828 and the Primary Sources tool suggests http://www.last.fm/music/Tylman+Susato/+similar as a source. However the name Georg Forster doesn't appear on http://www.last.fm/music/Tylman+Susato/+similar by the time I was editing and thus doesn't work as a reference for the purposes of Wikidata. 

If you want to reference dynamic websites like this, how about using achieve.org for more permanent links?

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148146

Moving forward, please drop your comments onto that Phabricator ticket.
