### ISSUE TITLE
ca.1510 get's falsely translated into 1510 without a qualifier

### ISSUE THREAD

**Issue by ChristianKleineidam** [Wikidata/primarysources#121]
http://imslp.org/wiki/Category:Forster,_Georg gives the data of birth as (ca.1510 — 12. November 1568).
Wikidata has the qualifier "sourcing circumstances" (P1480) with "circa" to include in cases like this. When The tool doesn't suggest it, it gives the appearance that the year is more certain in the source than it really is.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148145

Moving forward, please drop your comments onto that Phabricator ticket.
