### ISSUE TITLE
Setting for only showing sources in languages that I can check

### ISSUE THREAD

**Issue by ChristianKleineidam** [Wikidata/primarysources#122]
I personally don't speak Russian and therefore can't check whether the Primary Source tool correctly parsed a statement. I would prefer it when the tool only shows me sources in languages I can check (and takes the information from Babel).

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148144

Moving forward, please drop your comments onto that Phabricator ticket.
