### ISSUE TITLE
Add support for translation

### ISSUE THREAD

**Issue by sjoerddebruin** [Wikidata/primarysources#123]
It should be possible to translate at least the frontend part.

**Comment by ScottWUaS** [comment]
Great, Sjoerd!

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148143

Moving forward, please drop your comments onto that Phabricator ticket.
