### ISSUE TITLE
Large errors in brown.edu mapping(?)

### ISSUE THREAD

**Issue by sjoerddebruin** [Wikidata/primarysources#124]
See the suggestions on https://www.wikidata.org/wiki/Q17428400 for example, they make no sense.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148142

Moving forward, please drop your comments onto that Phabricator ticket.
