### ISSUE TITLE
Provide a way to see Wikidata and the source on the same page

### ISSUE THREAD

**Issue by ChristianKleineidam** [Wikidata/primarysources#125]
I think it would be valuable to have a view where the left side of the screen shows Wikidata and the right side of the screen shows the website to which the reference points. At best the website with an annotation that suggests which lines of the website are the reason for StrepHit thinking that it supports the fact.

Making it easier to see both Wikidata and the source at the same page will reduce the amount of time where a reference get's approved without the user looking at the source page.

**Comment by thadguidry** [comment]
This could alternatively be handled by the user's browser, if they had a plugin to produce that view.

**Comment by ChristianKleineidam** [comment]
Most users won't download plugins. Yet there a good chance that the current setup encourages many people do approve false references.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148140

Moving forward, please drop your comments onto that Phabricator ticket.
