### ISSUE TITLE
mathematical formulae extracted from English wikipedia displaying double slashes when uploaded on primary source tool

### ISSUE THREAD

**Issue by yash-nagar** [Wikidata/primarysources#127]
I extracted mathematical formulae from English wikipedia articles related to math (approximately 18,000). One example formula looks like the following:

\alpha_J = R_i - [R_f + \beta_{iM} \cdot (R_M - R_f)]

Then I used primary source tool to upload them on Wikidata. However, when I checked the same formula after uploading it on primary source tool, it looked like this:

\\alpha_J = R_i - [R_f + \\beta_{iM} \\cdot (R_M - R_f)]

All the single slashes were replaced by double slashes and due to this error, the formulas won't be approved. Is there any solution to this problem.
I have also attached the text file which contains all the formulas with their respective wikidata item number.
[formulalist.txt](https://github.com/Wikidata/primarysources/files/522450/formulalist.txt)

**Comment by GlorianY** [comment]
In order to ease us (WMDE) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148138

Moving forward, please drop your comments onto that Phabricator ticket.
