### ISSUE TITLE
Suggest new statements at the top of the page

### ISSUE THREAD

**Issue by mineo** [Wikidata/primarysources#38]
On https://www.wikidata.org/wiki/Q131285 you'll have to scroll through all the existing statements but not too far (because of the long list of sitelinks) to get to the suggested "genre" statements. It would be great if that could appear at the top to make scrolling unnecessary.

**Comment by tomayac** [comment]
As new claims, new references, and ultimately new qualifiers can occur anywhere on the Wikidata item page, one would have to scroll down anyway in most cases. We could maybe imagine an always visible navigation widget that would allow one to directly jump to the to-be-approved thing.

**Comment by tomayac** [comment]
Closed for the same reasons and rationale as https://github.com/google/primarysources/issues/106.

**Comment by tomayac** [comment]
Re-opening and tagging as 'open task'.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148184

Moving forward, please drop your comments onto that Phabricator ticket.
