### ISSUE TITLE
Reference URLs that are on meta's spam blacklist should not be suggested

### ISSUE THREAD

**Issue by mariushoch** [Wikidata/primarysources#49]
From time to time I see references that are on https://meta.wikimedia.org/wiki/Spam_blacklist, those should not be suggested as they can't be used on the Item, also they're probably not useful.

**Comment by tfmorris** [comment]
This filter should be applied further upstream in the data generation process.  It may be the case that another acceptable reference URL is available in its place.

**Comment by tomayac** [comment]
Assigning @vrandezo (as a proxy?), as @Tpt is currently no longer part of the Google organization.

**Comment by tfmorris** [comment]
Note: There is a blacklist which is used located at: https://www.wikidata.org/wiki/Wikidata:Primary_sources_tool/URL_blacklist
but it's focus is blacklisting sites which make for poor references, not sites which are associated with spam.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148181

Moving forward, please drop your comments onto that Phabricator ticket.
