### ISSUE TITLE
Statements should be added without reloading the page

### ISSUE THREAD

**Issue by Daniele** [Wikidata/primarysources#58]
The tool should be able to add statements without reloading the page. Right now, if I have to approve or reject 10 statements with 2 references each, the page reloads 30 times. When the page is reloaded it doesn't remember the exact position so I have to scroll to get back to where I was. This makes usage of the tool very time-consuming, not to mention the waste of bandwidth.

**Comment by addshore** [comment]
+1

**Comment by tfmorris** [comment]
:+1: Very annoying and inefficient.

**Comment by tomayac** [comment]
Closing for the same reasons and rationale as https://github.com/google/primarysources/issues/106.

**Comment by tomayac** [comment]
Re-opening and tagging as 'open task'.

**Comment by ChristianKleineidam** [comment]
I would expect that the usage of the tool would double if this would be fixed.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148179

Moving forward, please drop your comments onto that Phabricator ticket.
