### ISSUE TITLE
Promote good possible references in the UI

### ISSUE THREAD

**Issue by Tpt** [Wikidata/primarysources#63]
When we display possible references to add, we should maybe display first the ones from more trustfully websites.

Asked here: https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool#Blacklisting_versus_whitelisting.3F

**Comment by tomayac** [comment]
This has been archived on the [2015 talk page](https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool/Archive/2015#Blacklisting_versus_whitelisting.3F).

**Comment by tomayac** [comment]
I have started a [whitelist](https://www.wikidata.org/wiki/Wikidata:Primary_sources_tool/URL_whitelist). Who should fill it?

**Comment by lydiapintscher** [comment]
The editors. You can promote it in the next weekly summary for example: https://www.wikidata.org/wiki/Wikidata:Status_updates/Next

**Comment by tomayac** [comment]
Closing for the same reasons and rationale as https://github.com/google/primarysources/issues/106. Happy to merge Pull Requests if someone works on a visual makeover.

**Comment by tomayac** [comment]
Re-opening and tagging as 'open task'.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148178

Moving forward, please drop your comments onto that Phabricator ticket.
