### ISSUE TITLE
Invalid character encoding (non-UTF-8) for JSON string values

### ISSUE THREAD

**Issue by tfmorris** [Wikidata/primarysources#66]
The record returned by this query:

https://tools.wmflabs.org/wikidata-primary-sources/statements/all?state=blacklisted&limit=1&offset=3319

has the user name encoded in ISO Latin-1 instead of UTF-8.  This causes it be unparseable by JSON parsers.

The offending string is: Jean-Frédéric

**Comment by tfmorris** [comment]
Because offsets are relative to the most recent, rather than the earliest, the URL above no longer returns the relevant item.

**Comment by tomayac** [comment]
@wastl, is this (proper handling of UTF-8 usernames) something you could easily add to the back-end?

**Comment by wastl** [comment]
The backend is currently encoding agnostic, it only deals with bytes. If the data received was in ISO encoding, it stores ISO encoding in the database and happily returns the same bytes. The username in the query part of the URL, and the server has no way of determining the encoding used in URLs (only the content encoding can be specified).

Not sure what's the best way to deal with such issues. Is there any way in the frontend code to ensure the username is always sent as UTF-8?

**Comment by tfmorris** [comment]
Sounds like it needs to be fixed two places: 1) in the front end that is sending non-UTF8 data and 2) in the backend to catch other/future places where the front end misbehaves.

My reading of [RFC 3986](http://www.rfc-editor.org/rfc/rfc3986.txt) says that non-ASCII characters should be converted to UTF-8 and then percent-encoded if outside the US-ASCII range. This makes sense to me for this application too since without a known canonical character set there's no way to interpret the string (or produce valid JSON later).

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148177

Moving forward, please drop your comments onto that Phabricator ticket.
