### ISSUE TITLE
Don't offer merged identifers (ie URLs which are redirects)

### ISSUE THREAD

**Issue by tfmorris** [Wikidata/primarysources#72]
Many external identifier systems support the concept of merging two or more identifiers and redirecting all references to the "losers" to the "winning" canonical identifier.

In October 2015 users asked that two of these cases be handled: [OpenLibrary](https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool/Archive/2015#Open_Library_identifiers) and [MusicBrainz](https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool/Archive/2015#Redirecting_MusicBrainz_IDs)

The MusicBrainz example, Nirvana's [Polly](https://www.wikidata.org/wiki/Q1575153) has 485 suggested IDs which take many hours, perhaps days, to clear with the current UI.

I'm more familiar with the OpenLibrary/Freebase history and know that the OL identifiers were imported before OpenLibrary had implemented their "Merge Author" functionality, so it's known that a large number of the topics with multiple IDs now redirect to a single OL URL at openlibrary.org.  The merge process is incomplete though, so there may still be unmerged IDs, which I would suggest be retained.

As I'm familiar with both OpenLibrary and Freebase, I'm happy to create a translation table for OL identifiers if that would help fix this.

While there may be value in having all available identifiers (that's a more general Wikidata issue), I personally think it's out-of-scope. Regardless, they can be filled in automatically once a human has confirmed the initial match.

**Comment by tfmorris** [comment]
Examples of merged IDs: http://tools.wmflabs.org/wikidata-primary-sources/entities/Q991?state=wrong
Example of duplicate OL ID which has not yet been merged: https://openlibrary.org/authors/OL7178469A/Fyodor_Dostoyevsky
The canonical ID is OL22242A

**Comment by tomayac** [comment]
@Tpt Is this something that you can take into account for the next rounds of data pushes?

**Comment by tomayac** [comment]
Assigned @vrandezo (as a proxy?) as @Tpt is currently no longer part of the Google organization.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148176

Moving forward, please drop your comments onto that Phabricator ticket.
