### ISSUE TITLE
Add documentation on how to develop & test

### ISSUE THREAD

**Issue by tfmorris** [Wikidata/primarysources#77]
Perhaps developers who are familiar with Wikidata gadgets know how to do this automatically, but it would be a great help to new developers to have the ReadMe include information on how to set up a development environment, test with the version being developed rather than the production version, etc.

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148174

Moving forward, please drop your comments onto that Phabricator ticket.
