### ISSUE TITLE
IMDb links formatted incorrectly for suggested identifier

### ISSUE THREAD

**Issue by tfmorris** [Wikidata/primarysources#78]
When I was offered the IMDB identifier suggestion for https://www.wikidata.org/wiki/Q43926 the preview link was to http://www.imdb.com/nm2312479/ instead of the correct http://www.imdb.com/name/nm2312479/. Because this 404s, users will be tempted to reject the suggested statement when it's correct, it's just the URL formatter that's wrong. After I accepted the suggestion, the URL was correctly formatted.

I suspect the issue is that https://www.wikidata.org/wiki/Property:P345 has multiple possible URL formats, which appear to be disambiguated based on regex matching against the identifier. The "nm" prefix should trigger the "name" form of the URL.

**Comment by tfmorris** [comment]
p.s. This also effects the "Primary Sources statement list" view for P345.  Don't know if that's a separate piece of code or not.

**Comment by tfmorris** [comment]
Although the property definitions have regexs which could be used for mapping, the standard widget has the matching logic hardcoded (for performance?). https://www.wikidata.org/wiki/MediaWiki:Gadget-AuthorityControl.js

I'm not sure what the best solution is which minimizes coupling & code redundancy while also providing for future extensibility.

```
/**
 * Get the snak value formatted with a link.
 *
 * @param {number} numericPropertyId Refers to PROPERTIES.
 * @param {string} value
 */
function getLinkValueForString( numericPropertyId, value ) {
	var linkValue;

	switch ( Number( numericPropertyId ) ) {
	case 213: // ISNI
		linkValue = value.replace( / /g, '' );
		break;
	case 345: // IMDb
		linkValue = '/' + value;
		switch ( value.substring( 0, 2 ) ) {
		case 'nm':
			linkValue = 'name' + linkValue + '/';
			break;
		case 'tt':
			linkValue = 'title' + linkValue + '/';
			break;
		case 'ch':
			linkValue = 'character' + linkValue + '/';
			break;
		case 'ev':
			linkValue = 'event' + linkValue;
			break;
		case 'co':
			linkValue = 'company' + linkValue + '/';
			break;
		}
		break;
	case 502: // HURDAT
		linkValue = value.substring( 4, 8 ); // year
		if ( Number( linkValue ) <= 2005 ) {
			linkValue += '/'; // Brings a list for that year
			// For direct link, would need to append <name of hurricane>.[s]htlm
			// ex: http://www.nhc.noaa.gov/archive/2004/ALEX.shtml or 2001/ALLISON.html
		} else { // after 2005
			linkValue += '/' + value.substring( 0, 4 ).toLowerCase() + '/';
		}
		break;
	case 628: // E Number
		linkValue = value.substring( 1, 16 ); // Skip initial letter
		break;
	case 882: // FIPS
		linkValue = value;
		linkValue = linkValue.substr( 0, 2 ) + '/' + linkValue;
		break;
	case 1323: // TA98
		linkValue = value.substring( 1, 16 ); // Skip initial letter
		break;
	default:
		linkValue = value;
	}

	return linkValue;
}
```

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148173

Moving forward, please drop your comments onto that Phabricator ticket.
