### ISSUE TITLE
Use Redis for caching

### ISSUE THREAD

**Issue by wastl** [Wikidata/primarysources#92]
wmflabs offers a Redis cluster for caching purposes. We should use it instead of the local cache, as it is multi process safe and keeps caches over restarts.

Redis Homepage: http://redis.io/
Redox as C++ library: https://github.com/hmartiro/redox
Redis on WMFLabs: https://wikitech.wikimedia.org/wiki/Help:Tool_Labs#Redis

**Comment by GlorianY** [comment]
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148167

Moving forward, please drop your comments onto that Phabricator ticket.
